; CoolQ Assembly SDK
; MIT License
; Copyright (c) 2020 frc
; https://github.com/frc123/CoolQ-Assembly-SDK
; Documentation: https://github.com/frc123/CoolQ-Assembly-SDK/wiki

include		windows.inc
include		user32.inc
includelib	user32.lib
include		kernel32.inc
includelib	kernel32.lib
include		crypt32.inc
includelib	crypt32.lib
;↑↑↑↑↑↑↑↑↑↑ DO NOT REMOVE ↑↑↑↑↑↑↑↑↑↑
;↓↓↓↓↓ include header/lib hear ↓↓↓↓↓


